codepkg/objects/API_Config_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumerkey__c</fullName>
        <label>Consumerkey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>API Config Settings</label>
</CustomObject>

codepkg/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total_Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Discount__c</fullName>
        <label>Total_Discount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transaction_Count__c</fullName>
        <label>Transaction_Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/TransactionItem__c.object
<CustomObject>
    <fields>
        <fullName>Item_Cost__c</fullName>
        <label>Item_Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>TransactionItem</relationshipLabel>
        <relationshipName>TransactionItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TransactionItem</label>
    <nameField>
        <label>TransactionItem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TransactionItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/TransactionItemsTest.cls
@isTest
public class TransactionItemsTest {

    @isTest
    static void actionCodeControllerTests() {
        
        //set http mock        
        Test.setMock(HttpCalloutMock.class, new HttpMockClass());

        //custom setting
        API_Config_Settings__c testConf = new API_Config_Settings__c();
        testConf.Consumerkey__c = 'test123';
		testConf.Consumer_Secret__c = 'test321';
        testConf.Endpoint__c = 'https://www.google.com';
        insert testConf;
        
        
        //create test data
        //create transaction
        Transaction__c testTxn = new Transaction__c();
        testTxn.Total_Cost__c = 100;
        testTxn.Total_Discount__c = 10;
        testTxn.Transaction_Count__c = 2;
        
        insert testTxn;
        
        //create transaction item
        TransactionItem__c testTxnItem1 = new TransactionItem__c();
        testTxnItem1.Item_Cost__c = 50;
        testTxnItem1.Name = 'testTxnItem1';
        testTxnItem1.Transaction__c = testTxn.Id;
                
        insert testTxnItem1;
        
        TransactionItem__c testTxnItem2 = new TransactionItem__c();
        testTxnItem2.Item_Cost__c = 50;
        testTxnItem2.Name = 'testTxnItem2';
        testTxnItem2.Transaction__c = testTxn.Id;
                
        insert testTxnItem2;
        
        //update an item
        testTxnItem2.Item_Cost__c = 60;
        update testTxnItem2;

        
        
        

        
        
    }

    
}